import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Stack, useMediaQuery } from '@mui/material';
import { BigSlider } from './../components/Slider';
import { Note, Services, Interview, Animals } from './../components/Sections';
import { screens, Span } from '../utils/styling';
import { TransparentBtn } from './../components/Buttons';

export default function Home() {
  const tablet = useMediaQuery(`(max-width:${screens[1]}px)`)

  return (
    <div className={styles.container}>
      <Head>
        <title>Adak</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack marginTop={tablet ? "120px" : "160px"}>
        <BigSlider />
        <Services />
        <Note>
          <Span kind={`e${tablet ? 0 : 8}`} style={{textAlign: tablet ? 'center' : undefined}}>TÜM KREDI KARTLARI <Span kind={`w${tablet ? 0 : 8}`}>GEÇERLIDIR.</Span></Span>
          <TransparentBtn>
            Hemen İletişime Geç!
          </TransparentBtn>
        </Note>
        <Interview />
        <Note blood>
          <Span kind={`e${tablet ? 0 : 8}`} style={{textAlign: tablet ? 'center' : undefined}}>FAIZIEV KASAP OLARAK BAŞKA ŞUBEMIZ <Span kind={`w${tablet ? 0 : 8}`}>YOKTUR.</Span></Span>
          <TransparentBtn>
            Adresimiz İçin Tıklayın!
          </TransparentBtn>
        </Note>
        <Animals />
      </Stack>
    </div>
  )
}
